spring:
  application:
    name: batchchunk

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/batch_schema?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456789

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false